language: python
python: '2.7'
script: trial hamper
notifications:
  email: false
  irc:
    channels:
    - chat.freenode.org#hamper
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: BcFGullBLhUphourdrEqy0BX2e8S1mse38dCSHSrevQm/sxOQ1lNzpQyD1jtjwJmASKi/h7CRa6SkAMWMa8qXDZSDP6OCFdfWkKvT95IqVME8ft114RccX7fHNdKrfZMfdtiQZuCnkvT1IMFahzessSyLXnns3fDHjNp+46wR28=
  app: heroku-lug
  on:
    repo: mythmon/hamper
    branch: master
